data <- read.csv2("household_power_consumption.txt")
head(data, n = 2)
subdata <- subset(data, Date == "1/2/2007"| Date=="2/2/2007")
png(filename="plot1.png", width = 480, height = 480)
GAP<- as.numeric(gsub(",","",subdata$Global_active_power))
hist(GAP,main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col="red")
dev.off()